apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: quay.io/drsylent/cubix/block5v2/optional-frontend:springboot3
        env:
        - name: BACKEND_URL
          value: http://backend:8080
        ports:
        - containerPort: 8080
          name: web
