apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: op4-kube-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: frontend
        image: quay.io/drsylent/cubix/block5v2/optional-frontend:springboot3
        env:
        - name: BACKEND_URL
          value: http://backend:8080
        ports:
        - containerPort: 8080
          name: web
